services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: loki-demo/order-service:0.0.1
    container_name: order-service
    environment:
      SERVICE_NAME: order-service
      APP_ENV: prod
      APP_LOG_FILE: /var/log/apps/order-service/app.log
    volumes:
      - /var/log/apps/order-service:/var/log/apps/order-service
    restart: unless-stopped
