spring:
  application:
    name: ${SERVICE_NAME:order-service}
  main:
    banner-mode: off

app:
  env: ${APP_ENV:prod}
  log:
    file: ${APP_LOG_FILE:/var/log/apps/order-service/app.log}

logging:
  level:
    root: INFO
